### ISSUE TITLE
Serial not found

### ISSUE THREAD

**Issue by Ahmed4812** [mackorone/mms-arduino#1]
Mac:
I installed the pyserial with pip and I can use it in my other python projects, so I am sure that the library was installed properly.  But when I run the Main.py given from mms-arduino, for some reason, it can't find the serial module. In the terminal, I do ```python foo.py``` (which has the import serial) works but in mms ```python Main.py --por....``` doesn't.
Is there any manual way of importing it? I can't import from the library path since it asks for admins access and mms can't do that like a regular terminal. 
Any suggestions are highly appreciated.

**Comment by mackorone** [comment]
Hi! Thanks for your interest in the project. Unfortunately, I don't have enough information to help you. What's the specific error message your seeing? What steps have you tried so far? Etc.
